version: "3.6"

services:
  thisrepo-testing:
    image: "AI4_CICD_DOCKER_IMAGE"
    container_name: "${BUILD_TAG}"
    hostname: "${BUILD_TAG}"
    working_dir: /srv
    command: >
      sh -c "git config --global --add safe.directory /srv &&
             tail -f /dev/null"
    volumes:
      - type: bind
        source: ./
        target: /srv
